{{- if .Values.operator.enabled }}
apiVersion: v1
kind: Service
metadata:  
  labels:
    app.kubernetes.io/name: {{ .Values.operator.nameOverride | default "keycloak-operator" }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: quarkus
  name: {{ .Values.operator.fullnameOverride | default "keycloak-operator" }}

spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Values.operator.nameOverride | default "keycloak-operator" }}
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
{{- end }}
