apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-ingress
  namespace: keycloak
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

    # alb terminate TLS on port 443 and forward http to backend 8080
    #alb.ingress.kubernetes.io/backend-protocol: "HTTP"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/healthcheck-path: /health/ready
    alb.ingress.kubernetes.io/healthcheck-port: "9000"
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:[aws_account_id]:certificate/[cert_arn_id]"

spec:
  ingressClassName: alb
  rules:
    - host: auth.keycloak.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak-service-expose
                port:
                  number: 8080
