# Default values for Keycloak Operator 
domain: "auth.keycloak.me"
namespace: "keycloak"
metaname: "keycloak-operator"

operator:
  enabled: true
  namespace: keycloak  
  replicas: 1
  
  #metadata override
  nameOverride: "keycloak-operator"
  fullnameOverride: "keycloak-operator"

  image:
    repository: quay.io/keycloak/keycloak-operator
    tag: "26.4.5"
    pullPolicy: IfNotPresent

  keycloakImage: quay.io/keycloak/keycloak:26.4.5 

  resources:
    requests:
      cpu: 300m
      memory: 450Mi
    limits:
      cpu: 700m
      memory: 450Mi

# Default values for Keycloak deployments
keycloak:
  enabled: true
  namespace: keycloak
  replicas: 2

  #metadata override
  nameOverride: "keycloak"
  fullnameOverride: "keycloak"

  db:
    vendor: mariadb
    host: database-1.c6royoums8vm.us-east-1.rds.amazonaws.com
    port: 3306
    database: keycloakdbrds
    usernameSecret:
      name: keycloak-db-secret
      key: db-username
    passwordSecret:
      name: keycloak-db-secret
      key: db-password
    url: "jdbc:mariadb://database-1.c6royoums8vm.us-east-1.rds.amazonaws.com:3306/keycloakdbrds"
    pool:
      enabled: true
      init: 1
      min: 5
      max: 10
  http:
    httpPort: 8080
  hostname: auth.keycloak.me
  resources:
    enabled: true
    requests:
      cpu: 1200m
      memory: 500Mi
    limits:
      cpu: 1200m
      memory: 1024Mi

  startupProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 30
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 3
  livenessProbe:
    enabled: true
    initialDelaySeconds: 120
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 5   

# Default values for ALB Ingress
extingress:
  enabled: true
  classname: alb
  hostname: auth.keycloak.me
  port: 8080  
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

    # alb terminate TLS on port 443 and forward http to backend 8080
    #alb.ingress.kubernetes.io/backend-protocol: "HTTP"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/healthcheck-path: /health/ready
    alb.ingress.kubernetes.io/healthcheck-port: "9000"
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:376129838666:certificate/250d29cf-179b-46e5-901f-bfd4461e9c7a"
