apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-keycloak-operator-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - appname: keycloak-operator-eks
            namespace: keycloak

  template:
    metadata:
      name: '{{appname}}-gitops-dev'
      labels:
        System: KEYCLOAK-OPERATOR
    spec:
      project: default
      destination:
        namespace: '{{namespace}}'
       # server: https://kubernetes.default.svc
        server: https://1A1BE5EB269CCA0C00A4ACE5B454408F.gr7.us-east-1.eks.amazonaws.com
      source:
        repoURL: https://github.com/duykhanh2104/keycloak_vnb.git   # add your repo
        targetRevision: main                                                   # branch name
        path: argocd-helm-operator-eks
        helm:
          valueFiles:
            - values.yaml                                                          # values name
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
